[package]
name = "btdevscan"
version = "1.0.1"
edition = "2024"

[dependencies]
btleplug = "0.11"
clap = { version = "4.5.51", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
